language: go

go:
  - 1.9
  - tip

install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/golang/lint/golint
  - dep ensure

script:
  - make coverage && make lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
