sudo: required
language: go
services:
  - docker
go:
  - 1.9
  - tip
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - DOCKER_USER=stratumndocker
install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/golang/lint/golint
  - dep ensure
script:
  - make coverage lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    skip_cleanup: true
    script: docker login --username $DOCKER_USER --password $DOCKER_PASS && make build docker_images docker_push VERSION=$COMMIT
    on:
      go: 1.9
      branch: master
  - provider: script
    skip_cleanup: true
    script: docker login --username $DOCKER_USER --password $DOCKER_PASS && make build docker_images docker_push VERSION=$TRAVIS_TAG
    on:
      go: 1.9
      tags: true