[[constraint]]
  name = "github.com/tendermint/tendermint"
  version = "0.18.0"

[[constraint]]
  name = "github.com/tendermint/go-wire"
  source = "github.com/tendermint/go-amino"
  version = "~0.7.3"

[[constraint]]
  name = "github.com/tendermint/go-crypto"
  version = "^0.5.0"

[[constraint]]
  # Even a patch version update  breaks Tendermint 0.18.0
  name = "github.com/tendermint/tmlibs"
  version = "=0.8.1"

[[override]] 
  # This is required because Tendermint needs ~1.0.0
  # but Docker claims it needs ^0.4.
  name = "github.com/gogo/protobuf"
  version = "^1.0.0"

[[override]] 
  # This is required because Tendermint needs ~1.0.0
  name = "github.com/golang/protobuf"
  version = "^1.0.0"

[[override]] 
  # This is required because Tendermint needs ~1.7.3
  name = "google.golang.org/grpc"
  version = "^1.7.3"

[[constraint]]
  name = "github.com/stratumn/go-chainscript"
  version = "=1.0.1"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[override]] 
  # Otherwise `dep ensure` takes forever
  name = "github.com/aws/aws-sdk-go"
  version = "^1.15.52"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

[[constraint]]
  name = "go.elastic.co/apm"
  version = "1.2.0"
