[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-github"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.0"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/osext"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"
  branch = "master"

[[constraint]]
  name = "github.com/tendermint/abci"
  version = "0.10.0"

[[constraint]]
  name = "github.com/tendermint/go-wire"
  revision = "b6fc872b42d41158a60307db4da051dd6f179415"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  version = "0.16.0"

[[constraint]]
  name = "github.com/tendermint/tmlibs"
  version = "0.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/xeipuuv/gojsonschema"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/golang/mock"
  branch="master"
  
[[constraint]]
  name = "github.com/google/go-querystring"
  branch="master"

[[constraint]]
  name = "github.com/jmespath/go-jmespath"
  branch="master"

[[override]] 
  # This is required because Tendermint needs v0.5
  # but Docker claims it needs v0.4 (but probably not intentionnally)
  name = "github.com/gogo/protobuf"
  version = "v0.5"

[[constraint]]
  name = "github.com/manifoldco/promptui"
  branch = "master"

[[override]]
  name = "github.com/chzyer/readline"
  branch = "fix-bell"
  source = "github.com/stratumn/readline"
