[[constraint]]
  name = "github.com/tendermint/go-wire"
  source = "github.com/tendermint/go-amino"
  version = "~0.7.3"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  version = "0.18.0"

[[override]] 
  # This is required because Tendermint needs ~1.0.0
  # but Docker claims it needs ^0.4.
  name = "github.com/gogo/protobuf"
  version = "^1.0.0"

[[override]] 
  # This is required because Tendermint needs ~1.0.0
  name = "github.com/golang/protobuf"
  version = "^1.0.0"

[[constraint]]
  name = "go.opencensus.io"
  version = "^0.17.0"

[[constraint]]
  name = "github.com/stratumn/go-chainscript"
  version = "=1.0.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"
