[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-github"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/osext"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  #branch = "master"
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/tendermint/abci"
  version = "0.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/tendermint/merkleeyes"

[[constraint]]
  name = "github.com/tendermint/go-wire"
  version = "0.6.2"

[[constraint]]
  branch = "develop"
  name = "github.com/tendermint/tendermint"
  #version = "0.11.0"

[[constraint]]
  name = "github.com/tendermint/tmlibs"
  version = "0.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/xeipuuv/gojsonschema"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "release"
  name = "github.com/hyperledger/fabric"

[[override]]
  branch = "master"
  name = "github.com/op/go-logging"

[[override]]
  name = "github.com/fsouza/go-dockerclient"
  revision = "d433254bb83b41d7072ce470e312ea3cee257882"
