version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    volumes:
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana/:/usr/share/kibana/config:ro
    depends_on:
      - elasticsearch
  apm-server:
    image: docker.elastic.co/apm/apm-server:6.6.0
    user: root
    ports:
      - "8200:8200"
    volumes:
      - ./config/apm/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    depends_on:
      - elasticsearch
